# Generated by Django 3.0.2 on 2020-10-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open', models.BigIntegerField(blank=True, null=True)),
                ('high', models.BigIntegerField(blank=True, null=True)),
                ('low', models.BigIntegerField(blank=True, null=True)),
                ('close', models.BigIntegerField(blank=True, null=True)),
                ('diff', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_price',
                'managed': False,
            },
        ),
    ]
