# Generated by Django 3.0.2 on 2020-10-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('code', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('open', models.BigIntegerField(blank=True, null=True)),
                ('high', models.BigIntegerField(blank=True, null=True)),
                ('low', models.BigIntegerField(blank=True, null=True)),
                ('close', models.BigIntegerField(blank=True, null=True)),
                ('diff', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'merge',
                'managed': False,
            },
        ),
    ]
